### ISSUE TITLE
Why only linear layers are used in the Morph block?

### ISSUE THREAD

**Issue by zhshj0110** [MTLab/MorphMLP#3]
Thanks for your excellent work MorphMLP. It offer a new model paradigm for deep learning research and inspire me a lot.
However, in your code,  both in the MorphFC_S block and MorphFC_T block, there are just linear layers used to model the spatial temporal relation. 
As far as we know, it is very easy to overfit for the linear layer, so we always use ReLU or GelU activation function and dropout layer to avoid overfitting. It is not intuitive for the model design, and confuse me a lot. 
Can you share me thought about why you design the model like this?
Thanks for your source code， which promote my new work a lot.
Wish you a happy life and a smooth work！

**Comment by junhaozhang98** [comment]
Thanks for your question.

Here are some motivations.

1. Since MLP can achieve promising result on image domain, we want to explore whether mlp can work on video as well.
2. Self-attention layer also need activation funcation and dorp out  to alleviate overfitting. We want to explore what's key of model architecture design?   operator? e.g., self-attention or fc layer so that are dynamic relations acquired by self attention necessary?   local-to global pattern?  Many papers(e.g., our work and Uniformer) show that local to global pattern is quite efficient and powerful.

Hope these can help you.

**Comment by zhshj0110** [comment]
OK，Thanks for your answer.
